# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 06:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'In-Progress'), (3, 'Resolved'), (4, 'Closed')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
